version: '3.8'

services:
  # Database - GUNAKAN OFFICIAL MYSQL IMAGE
  database:
    image: mysql:8.0  # ← GANTI ke official image
    container_name: eai_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eai_user_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/sql-init:/docker-entrypoint-initdb.d  # ← Mount SQL init scripts
    networks:
      - eai_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # User Service
  user-service:
    image: adriandeka18/eai-uas-user-service:latest
    container_name: eai_user_service
    ports:
      - "3001:3001"
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eai_user_service
      - JWT_SECRET=your_very_secure_jwt_secret_key_here
      - GRAPHQL_PORT=4001
    depends_on:
      database:
        condition: service_healthy
    networks:
      - eai_network

  # Menu Service
  menu-service:
    image: adriandeka18/eai-uas-menu-service:latest
    container_name: eai_menu_service
    ports:
      - "3002:3002"
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eai_menu_service
      - JWT_SECRET=your_very_secure_jwt_secret_key_here
      - GRAPHQL_PORT=4002
      - USER_SERVICE_GRAPHQL_URL=http://user-service:4001/graphql
      - ORDER_SERVICE_GRAPHQL_URL=http://order-service:4003/graphql
      - MOVIE_SERVICE_URL=http://tubes_eai_gateway:5000/graphql
      - BOOK_SERVICE_URL=http://book_service:5004/graphql  # NEW: Book service URL
    depends_on:
      - database
      - user-service
    networks:
      - eai_network
      - shared-network

  # Order Service
  order-service:
    image: adriandeka18/eai-uas-order-service:latest
    container_name: eai_order_service
    ports:
      - "3003:3003"
      - "4003:4003"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eai_order_service
      - JWT_SECRET=your_very_secure_jwt_secret_key_here
      - GRAPHQL_PORT=4003
      - USER_SERVICE_GRAPHQL_URL=http://user-service:4001/graphql
      - MENU_SERVICE_GRAPHQL_URL=http://menu-service:4002/graphql
    depends_on:
      - database
      - user-service
      - menu-service
    networks:
      - eai_network

  # Review Service
  review-service:
    image: adriandeka18/eai-uas-review-service:latest
    container_name: eai_review_service
    ports:
      - "3004:3004"
      - "4004:4004"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eai_review_service
      - JWT_SECRET=your_very_secure_jwt_secret_key_here
      - GRAPHQL_PORT=4004
      - GEMINI_API_KEY=AIzaSyAXS8eIgErpAKQwOHInLOYqxDWvk0stSb0
      - USER_SERVICE_GRAPHQL_URL=http://user-service:4001/graphql
      - MENU_SERVICE_GRAPHQL_URL=http://menu-service:4002/graphql
      - ORDER_SERVICE_GRAPHQL_URL=http://order-service:4003/graphql
    depends_on:
      - database
      - user-service
      - menu-service
      - order-service
    networks:
      - eai_network

  # Payment Service
  payment-service:
    image: adriandeka18/eai-uas-payment-service:latest
    container_name: eai_payment_service
    ports:
      - "3005:3005"
      - "4005:4005"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eai_payment_service
      - JWT_SECRET=your_very_secure_jwt_secret_key_here
      - GRAPHQL_PORT=4005
      - USER_SERVICE_GRAPHQL_URL=http://user-service:4001/graphql
      - ORDER_SERVICE_GRAPHQL_URL=http://order-service:4003/graphql
      - MIDTRANS_SERVER_KEY=SB-Mid-server-shvTgYmhMAh714s-7RusJRw6
      - MIDTRANS_CLIENT_KEY=SB-Mid-client-FwpyUrEkhEM5HaF2
      - MIDTRANS_IS_PRODUCTION=false
    depends_on:
      - database
      - user-service
      - order-service
    networks:
      - eai_network

  # Frontend - GUNAKAN OFFICIAL NGINX IMAGE
  frontend:
    image: nginx:alpine  # ← GANTI ke official image
    container_name: eai_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/views:/usr/share/nginx/html  # ← Mount frontend files
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # ← Mount nginx config
    networks:
      - eai_network

volumes:
  mysql_data:

networks:
  eai_network:
    driver: bridge
  shared-network: # ← TAMBAHKAN: Deklarasi jaringan eksternal
    external: true