services:
  mysql:
    image: mysql:8
    container_name: mysql-payment
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: eai_payment_service
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./eai_payment_service.sql:/docker-entrypoint-initdb.d/eai_payment_service.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eai-network

  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "3005:3005"      # REST
      - "4005:4005"      # GraphQL
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: npm run dev:both
    networks:
      - eai-network

volumes:
  mysql-data:
  
networks:
  eai-network:
    driver: bridge