services:
  mysql:
    image: mysql:8
    container_name: mysql-menu
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: eai_menu_service
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./eai_menu_service.sql:/docker-entrypoint-initdb.d/eai_menu_service.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eai-network

  menu-service:
    build: .
    container_name: menu-service
    ports:
      - "3002:3002"      # REST
      - "4002:4002"      # GraphQL
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: npm run dev:both
    networks:
      - eai-network

volumes:
  mysql-data:
  
networks:
  eai-network:
    driver: bridge